#!/bin/sh

# Set these paths appropriately

BIN=/home/gio/GitHub/Python-IFG/treetagger/bin
CMD=/home/gio/GitHub/Python-IFG/treetagger/cmd
LIB=/home/gio/GitHub/Python-IFG/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
