#!/bin/sh

# Set these paths appropriately

BIN=/home/gio/GitHub/Python-IFG/treetagger/bin
CMD=/home/gio/GitHub/Python-IFG/treetagger/cmd
LIB=/home/gio/GitHub/Python-IFG/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
